apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/techdocs-ref: ./
  description: 'LAB: Large-scale Alignment for chatBots is a novel synthetic data-based
    alignment tuning method for LLMs from IBM Research. Granite-8b-lab-v1 is a Granite-8b-base
    derivative model trained with the LAB methodology, using Mixtral-8x7b-Instruct
    as a teacher model.'
  links:
  - icon: WebAsset
    title: API URL
    type: website
    url: https://granite-31-8b-lab-v1-140-v1-ggmtest.apps.gmontero416.devcluster.openshift.com
  - icon: WebAsset
    title: predictor FastAPI URL
    type: website
    url: https://granite-31-8b-lab-v1-140-v1-predictor-ggmtest.apps.gmontero416.devcluster.openshift.com/docs
  - icon: WebAsset
    title: predictor model serving URL
    type: website
    url: https://granite-31-8b-lab-v1-140-v1-predictor-ggmtest.apps.gmontero416.devcluster.openshift.com
  - icon: WebAsset
    type: website
    url: oci://registry.redhat.io/rhelai1/modelcar-granite-3-1-8b-lab-v1:1.4.0
  name: granite-3.1-8b-lab-v1-1.4.0
spec:
  dependsOn:
  - resource:v1
  - api:v1
  lifecycle: development
  owner: user:kube:admin
  profile:
    displayName: granite-3.1-8b-lab-v1-1.4.0
  type: model-server
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  annotations:
    backstage.io/techdocs-ref: resource/
  description: 'LAB: Large-scale Alignment for chatBots is a novel synthetic data-based
    alignment tuning method for LLMs from IBM Research. Granite-8b-lab-v1 is a Granite-8b-base
    derivative model trained with the LAB methodology, using Mixtral-8x7b-Instruct
    as a teacher model.'
  links:
  - icon: WebAsset
    type: website
    url: oci://registry.redhat.io/rhelai1/modelcar-granite-3-1-8b-lab-v1:1.4.0
  name: v1
spec:
  dependencyOf:
  - component:granite-3.1-8b-lab-v1-1.4.0
  lifecycle: development
  owner: user:kube:admin
  profile:
    displayName: v1
  type: ai-model
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  annotations:
    backstage.io/techdocs-ref: api/
  description: 'LAB: Large-scale Alignment for chatBots is a novel synthetic data-based
    alignment tuning method for LLMs from IBM Research. Granite-8b-lab-v1 is a Granite-8b-base
    derivative model trained with the LAB methodology, using Mixtral-8x7b-Instruct
    as a teacher model.'
  links:
  - icon: WebAsset
    title: API URL
    type: website
    url: https://granite-31-8b-lab-v1-140-v1-ggmtest.apps.gmontero416.devcluster.openshift.com
  - icon: WebAsset
    title: predictor FastAPI URL
    type: website
    url: https://granite-31-8b-lab-v1-140-v1-predictor-ggmtest.apps.gmontero416.devcluster.openshift.com/docs
  - icon: WebAsset
    title: predictor model serving URL
    type: website
    url: https://granite-31-8b-lab-v1-140-v1-predictor-ggmtest.apps.gmontero416.devcluster.openshift.com
  name: granite-3.1-8b-lab-v1-1.4.0
spec:
  definition: no-definition-yet
  dependencyOf:
  - component:granite-3.1-8b-lab-v1-1.4.0
  lifecycle: development
  owner: user:kube:admin
  profile:
    displayName: granite-3.1-8b-lab-v1-1.4.0
  type: openapi
