apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/techdocs-ref: ./
  description: A custom Red Hat base model instruct tuned only for phase 00, produced
    by IBM Research specifically for RHEL AI.
  links:
  - icon: WebAsset
    title: API URL
    type: website
    url: https://granite-3-1-8b-starter-v1-1-4-0-2025-03-31t193928476z-ggmtest.apps.gmontero416.devcluster.openshift.com
  - icon: WebAsset
    type: image
    url: oci://registry.redhat.io/rhelai1/modelcar-granite-3-1-8b-starter-v1:1.4.0
  name: granite-3.1-8b-starter-v1-1.4.0
spec:
  dependsOn:
  - resource:v1
  - api:v1
  lifecycle: development
  owner: user:kube:admin
  profile:
    displayName: granite-3.1-8b-starter-v1-1.4.0
  type: model-server
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  annotations:
    backstage.io/techdocs-ref: resource/
  description: A custom Red Hat base model instruct tuned only for phase 00, produced
    by IBM Research specifically for RHEL AI.
  links:
  - icon: WebAsset
    type: website
    url: oci://registry.redhat.io/rhelai1/modelcar-granite-3-1-8b-starter-v1:1.4.0
  name: v1
spec:
  dependencyOf:
  - component:granite-3.1-8b-starter-v1-1.4.0
  lifecycle: development
  owner: user:kube:admin
  profile:
    displayName: v1
  type: ai-model
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  annotations:
    backstage.io/techdocs-ref: api/
  description: A custom Red Hat base model instruct tuned only for phase 00, produced
    by IBM Research specifically for RHEL AI.
  links:
  - icon: WebAsset
    title: API URL
    type: website
    url: https://granite-3-1-8b-starter-v1-1-4-0-2025-03-31t193928476z-ggmtest.apps.gmontero416.devcluster.openshift.com
  - icon: WebAsset
    type: image
    url: oci://registry.redhat.io/rhelai1/modelcar-granite-3-1-8b-starter-v1:1.4.0
  name: granite-3.1-8b-starter-v1-1.4.0
spec:
  definition: no-definition-yet
  dependencyOf:
  - component:granite-3.1-8b-starter-v1-1.4.0
  lifecycle: development
  owner: user:kube:admin
  profile:
    displayName: granite-3.1-8b-starter-v1-1.4.0
  type: openai
